export const FILM_STATUS = {
    PENDING: "pending",
    APPROVED: "approved",
    REJECTED: "rejected",
};

export const ALLOWED_TRANSITIONS = {
    [FILM_STATUS.PENDING]: [FILM_STATUS.APPROVED, FILM_STATUS.REJECTED],
    [FILM_STATUS.APPROVED]: [FILM_STATUS.REJECTED],
    [FILM_STATUS.REJECTED]: [FILM_STATUS.APPROVED],
};