export const FILM_STATUS = {
    PENDING: "pending",
    APPROVED: "approved",
    REJECTED: "rejected",
    SELECTED: "selected",
};

export const ALLOWED_TRANSITIONS = {
    [FILM_STATUS.PENDING]: [FILM_STATUS.APPROVED, FILM_STATUS.REJECTED],
    [FILM_STATUS.APPROVED]: [FILM_STATUS.REJECTED, FILM_STATUS.SELECTED],
    [FILM_STATUS.REJECTED]: [FILM_STATUS.APPROVED],
    [FILM_STATUS.SELECTED]: [FILM_STATUS.APPROVED, FILM_STATUS.REJECTED],
};
